spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${DB_HOST:jdbc:postgresql://postgres:5432/customer_statements}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      region:
        static: ${REGION:af-south-1}
app:
  s3:
    bucket-name: ${BUCKET_NAME}
  jwt:
    secret: ${JWT_SECRET:6Z8oQGGas4y2sJM86rNpgLIybss1IotZbrW60qlL2Jm}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n%ex{3, org.springframework, org.apache, org.hibernate, com.zaxxer, jdk.internal, java.base}"
